name: "Prepare Environment"
description: "Prepare the development environment for the other actions"

runs:
  using: "composite"
  steps:
    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: 3.11

    - name: Install Dev Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements-dev.txt
