name: Black
on: [ pull_request, workflow_dispatch ]

jobs:
  black:
    name: Black Validation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare Environment
      uses: ./.github/actions/prepare-environment
      with:
        python-version: 3.11
        setup-type: dev
    - name: Validate using Black
      run: |
        make check-black
