name: Isort
on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    name: Isort Validation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare Environment
      uses: ./.github/actions/prepare-environment
    - name: Validate using Isort
      run: |
        make check-isort
