name: Isort
on: [ pull_request, workflow_dispatch ]

jobs:
  isort:
    name: Isort Validation
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Prepare Environment
      uses: ./.github/actions/prepare-environment
      with:
        python-version: 3.11
        setup-type: dev
    - name: Validate using Isort
      run: |
        make check-isort
