name: Pytest
on: [ pull_request, workflow_dispatch ]

jobs:
  build:
    name: Pytest Validation
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Prepare Environment
      uses: ./.github/actions/prepare-environment
    - name: Test the code with pytest
      run: |
        make pytest
